workflows:
    simulator-native-ios:
        name: iOS simulator build
        max_build_duration: 120
        instance_type: mac_mini
        environment:
            vars:
               XCODE_PROJ: "NetflixClone.xcodeproj" # <-- Put the name of your Xcode workspace here
               XCODE_SCHEME: "NetflixClone" # <-- Put the name of your Xcode scheme here
            xcode: 13.0
        scripts:
            - name: Build ipa for distribution
              script: |
                                - xcode-project build-ipa --project "$XCODE_PROJ" --scheme "$XCODE_SCHEME"
