
workflows:
	netflix-clone-workflow:
		name: netflix-pipeline
		environment:
		vars:
		XCODE_PROJ: "NetflixClone.xcodeproj"
		XCODE_SCHEME: "NetflixClone" # <-- Put the name of your Xcode scheme here
		xcode: 13.0
		scripts:
		- name: Build ipa for distribution
		script: | xcodebuild build -scheme "$XCODE_SCHEME" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.5' -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
			
			- name: Build debug ipa
				script: | - xcode-project build-ipa --project "$XCODE_SCHEME" --scheme "$XCODE_SCHEME"
		publishing:
			email:
				recepients:
					- rizosamuel1995@gmail.com
